money_flow/entities/urls.py
from django.urls import include, path

from . import views

app_name = "entities"

moneyflowpatterns = [
    path(
        "create/", views.MoneyFlowCreateView.as_view(), name="moneyflow_create"
    ),
    path(
        "<int:pk>/update/",
        views.MoneyFlowUpdateView.as_view(),
        name="moneyflow_update",
    ),
    path(
        "<int:pk>/delete/",
        views.MoneyFlowDeleteView.as_view(),
        name="moneyflow_delete",
    ),
]

statuspatterns = [
    path("create/", views.StatusCreateView.as_view(), name="status_create"),
    path(
        "<int:pk>/update/",
        views.StatusUpdateView.as_view(),
        name="status_update",
    ),
    path(
        "<int:pk>/delete/",
        views.StatusDeleteView.as_view(),
        name="status_delete",
    ),
    path("", views.StatusTableView.as_view(), name="status_list"),
]


typepatterns = [
    path("create/", views.TypeCreateView.as_view(), name="type_create"),
    path(
        "<int:pk>/update/", views.TypeUpdateView.as_view(), name="type_update"
    ),
    path(
        "<int:pk>/delete/", views.TypeDeleteView.as_view(), name="type_delete"
    ),
    path("", views.TypeTableView.as_view(), name="type_list"),
]


categoriespatterns = [
    path(
        "create/", views.CategoryCreateView.as_view(), name="category_create"
    ),
    path(
        "<int:pk>/update/",
        views.CategoryUpdateView.as_view(),
        name="category_update",
    ),
    path(
        "<int:pk>/delete/",
        views.CategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path("", views.CategoryTableView.as_view(), name="category_list"),
]


subcategoriespatterns = [
    path(
        "create/",
        views.SubCategoryCreateView.as_view(),
        name="subcategory_create",
    ),
    path(
        "<int:pk>/update/",
        views.SubCategoryUpdateView.as_view(),
        name="subcategory_update",
    ),
    path(
        "<int:pk>/delete/",
        views.SubCategoryDeleteView.as_view(),
        name="subcategory_delete",
    ),
    path("", views.SubCategoryTableView.as_view(), name="subcategory_list"),
]


urlpatterns = [
    path("", views.MoneyFlowTableView.as_view(), name="moneyflow_list"),
    path("subcategories/", include(subcategoriespatterns)),
    path("categories/", include(categoriespatterns)),
    path("moneyflow/", include(moneyflowpatterns)),
    path("status/", include(statuspatterns)),
    path("type/", include(typepatterns)),
]

money_flow/money_flow/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("chaining/", include("smart_selects.urls")),
    path("", include("entities.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

money_flow/templates/status/status_create.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<h1>{% if flow %}Редактировать{% else %}Добавить{% endif %} запись</h1>
<div class="card col-5">
    <form method="post">
        {% csrf_token %}
        {{ form.media.js }}
        {% bootstrap_form form %}
        {% bootstrap_button button_type="submit" content="Сохранить" %}
    </form>
</div>
<a href="{% url 'entities:status_list' %}">Назад к списку</a>
{% endblock %}

money_flow/templates/status/status_delete.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<h1>Удалить запись</h1>
<p>Вы уверены, что хотите удалить статус?</p>
<form method="post">
    {% csrf_token %}
    {% bootstrap_button button_type="submit" content="Да, удалить" %}
    <a href="{% url 'entities:status_list' %}">Отмена</a>
</form>
{% endblock %}

money_flow/templates/status/status_list.html
{% extends "base.html" %}
{% load django_bootstrap5 %}
{% block content %}
<h1>Статусы</h1>
<table border="1" cellpadding="5" cellspacing="0">
    <thead>
        <tr>
            <th>ID</th>
            <th>Название</th>
        </tr>
    </thead>
    <tbody>
        {% for status in statuses %}
        <tr>
            <td>{{ status.id }}</td>
            <td>{{ status.name }}</td>
            <td>
                <a href="{% url 'entities:status_update' status.pk %}">✏️</a>
                <a href="{% url 'entities:status_delete' status.pk %}">🗑️</a>
            </td>
        </tr>
        {% empty %}
        <tr><td colspan="2">Нет данных</td></tr>
        {% endfor %}
    </tbody>
</table>
<a href="{% url 'entities:status_create' %}" class="add-button btn btn-primary">➕ Добавить запись</a>
{% endblock %}